gpio: properly accept timeout=None in GPIO.poll()
Calling poll of an epoll instance with timeout being None triggers a
TypeError:

	$ python -c 'import select; select.epoll().poll(timeout=None)'
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	TypeError: a float is required

Fix this by passing -1 as timeout if None is given which has the
semantic of wait indefinitely.

Closes: https://github.com/vsergeev/python-periphery/issues/29